### PR TITLE
Fix featured image in WP 4.5

### LINKED ISSUE #108: After Featured image is added in Customizer, error displays in WP Admin Featured image
**Test Steps**
Navigate to `{removed link}` and login
Click on Pages then >Add new page - WP only - Featured image
View Featured image box
_**Expected:**_
The featured image interface in WP Admin displays without error and works to upload a featured image

**Actual:**
On navigating to a new page, (even prior to saving the page) the Featured image box displays with error message - Warning: Missing argument 3 for WP_Customize_Featured_Image_Controller::filter_admin_post_thumbnail_html() in /srv/bindings/327e7c8b5e2b477ba002a93d24b46535/code/wp-content/plugins/customize-posts/php/class-wp-customize-featured-image-controller.php on line 189

newpagefeaturedimageerror

NB: the featured image functionality was working in WP Admin, prior to the customizer update to add the featured image in customizer.

### PR DESCRIPTION
**Pull request by valendesigns**
Fixes #108

### CODE REVIEW

File: php/class-wp-customize-featured-image-controller.php [hunk 1]
```diff
@@ -186,7 +206,10 @@ public function handle_save_post_thumbnail_id( $post_id ) {
 	 * @param int    $thumbnail_id Thumbnail ID.
 	 * @return string Content.
 	 */
-	public function filter_admin_post_thumbnail_html( $content, $post_id, $thumbnail_id ) {
+	public function filter_admin_post_thumbnail_html( $content, $post_id, $thumbnail_id = null ) {
+		if ( is_null( $thumbnail_id ) ) {
+			$thumbnail_id = $this->thumbnail_id;
```
Comment (westonruter) [inline php/class-wp-customize-featured-image-controller.php]: Would this be better as just `$thumbnail_id = get_post_thumbnail_id( $post_id );` instead of adding the `set_admin_post_thumbnail_id` function above?

File: php/class-wp-customize-featured-image-controller.php [hunk 2]
```diff
@@ -171,6 +180,17 @@ public function handle_save_post_thumbnail_id( $post_id ) {
...
 
 	/**
+	 * Sets the current thumbnail ID.
+	 *
+	 * Executed during the `admin_post_thumbnail_size` hook to supply the current thumbnail ID
+	 * in WordPress < 4.6 where the third parameter in `admin_post_thumbnail_html` does not exist.
+	 */
+	public function set_admin_post_thumbnail_id( $size, $thumbnail_id, $post ) {
+		unset( $size, $post );
+		$this->thumbnail_id = $thumbnail_id;
```
Comment (westonruter) [inline php/class-wp-customize-featured-image-controller.php]: If this filter is to be used, it needs to return the `$size` here. It is getting lost otherwise.

File: js/customize-preview-featured-image.js [hunk 3]
```diff
@@ -35,7 +35,7 @@ var CustomizePreviewFeaturedImage = (function( api, $ ) {
 		refresh: function() {
 			var partial = this, setting, refreshPromise;
 			setting = api( partial.params.primarySetting );
-			if ( '' === setting() ) {
+			if ( '' === setting() || -1 === setting() ) {
```
Comment (westonruter) [inline js/customize-preview-featured-image.js]: See my comment here: https://github.com/xwp/wp-customize-posts/issues/108#issuecomment-215110422

File: php/class-wp-customize-featured-image-controller.php (hunk 1 above)
Comment (valendesigns) [inline php/class-wp-customize-featured-image-controller.php]: That doesn't work unfortunately. When you add the featured image via the edit post page the hidden input does not get the correct ID set in WP 4.5.

File: php/class-wp-customize-featured-image-controller.php (hunk 2 above)
Comment (valendesigns) [inline php/class-wp-customize-featured-image-controller.php]: Good catch, fixing it now.

File: php/class-wp-customize-featured-image-controller.php (hunk 1 above)
Comment (westonruter) [inline php/class-wp-customize-featured-image-controller.php]: I see, because we're blocking the attachment ID from being saved, and so `get_post_thumbnail_id()` won't return the right thing until the post has been saved.
