### PR TITLE
Fix purgeTrash by setting active to false

### LINKED ISSUE #164: Trashed post section unexpectedly appears at root upon customize-save
Defect in 0.6.0:

1. Change a post's status to trash
2. Publish
3. Collapse the Posts panel to see the root of the Customizer.
4. See the trashed post section unexpectedly appear in the root.

trashed-post-root-section

### PR DESCRIPTION
**Pull request by valendesigns**
Fixes #164

### CODE REVIEW

File: js/customize-posts.js [hunk 1]
```diff
@@ -240,8 +240,8 @@
 		api.section.each( function( section ) {
 			if ( section.extended( component.PostSection ) && 'trash' === api( section.id ).get().post_status ) {
 				api.section.remove( section.id );
+				section.active.set( false );
```
Comment (westonruter) [inline js/customize-posts.js]: Should we also just eliminate the section entirely from the DOM?

Comment (westonruter) [inline js/customize-posts.js]: Like `section.container.remove()`?
