### PR TITLE
Fix selecting input for newly-inserted post's first control

### LINKED ISSUE #209: Title Focus Issue While Creating New Posts
This is UX flow issue. When I click the <kbd>+</kbd> button to create a new post, the first thing I want to do is add a title. Here's where I face a UX glitch.

Current UX-Flow
- Click the <kbd>+</kbd> button
- Either press <kbd>tab</kbd> to select the title or click on the title (which BTW doesn't pre-select the existing value i.e. `(no title)`) and add a new title.

Better UX-Flow would be:
- Click the <kbd>+</kbd> button
- The title element is pre-focused, i.e. `(no title)` value is pre-selected and all I have to do is type the title.

### PR DESCRIPTION
**Pull request by westonruter**
This probably failed with the switch to embedding controls upon expanding a post section.

Fixes #209.

### CODE REVIEW

File: js/customize-post-section.js [hunk 1]
```diff
@@ -341,6 +341,15 @@
 			section.postFieldControls.post_title = control;
 			api.control.add( control.id, control );
 
+			// Select the input's contents when the value is a placeholder.
+			control.deferred.embedded.done( function() {
+				control.container.find( ':input' ).on( 'focus', function() {
```
Comment (sayedwp) [inline js/customize-post-section.js]: @westonruter What is the use of selecting all input/textarea/select/button ( `:input` ) when post title field will only be input?  I mean why not just use `input` ?

Comment (westonruter) [inline js/customize-post-section.js]: True. It could just be `input`.
